improving token config and create bindingJSON utils
divisi-developer-poros/poros-web-backend pull request #7
Opened 2020-09-23 00:17 UTC by huf0813

Hi, i see a lot of insight from @Endrawan and @AFauzulh for better code. Thx guys, i hope there will be more discussions later

2020-09-24 08:48 UTC, Endrawan requested changes
Thank you for your token improvement @huf0813 . But i still don't understand why you need to create that BindingJSON() method. Maybe you could enlighten me a little?

2020-09-24 08:48 UTC, Endrawan commented on controllers/testing/test_handler.go
> +	if err := cobs.Binding.BindingJSON(c, &userCobs); err != nil {
Why not use `ShouldBindJSON()` ?

2020-09-24 08:48 UTC, Endrawan commented on utils/bind/bind.go
> +}
Is this really necessary? I mean gin already provided `ShouldBindJSON()` , which exactly works like this

2020-09-24 11:30 UTC, huf0813 commented
As you can see on docs. `BindJSON()` by default will implements two methods, they are `ShouldBindWith()` and `AbortWithError()`. If we just implement just `ShouldBindJSON()` then we will missing something important, that is **error handling**. That's why i create utils for those.

docs :
1. [Binding Model](https://github.com/gin-gonic/gin#model-binding-and-validation)
2. [BindJSON()](https://godoc.org/github.com/gin-gonic/gin#Context.BindJSON)
3. [ShouldBindJSON()](https://godoc.org/github.com/gin-gonic/gin#Context.ShouldBindJSON)
4. [ShoulBindWIth()](https://godoc.org/github.com/gin-gonic/gin#Context.ShouldBindWith)

2020-09-24 14:28 UTC, Endrawan commented
Okay, but the problem is lies in `c.AbortWithError()` you called in `BindingJSON()`. When you called `c.AbortWithError()`, it will force our server to return a header (in your code its StatusBadRequest). So when we want to change the header to the correct one (for example StatusNotFound), it'll return a warning `Headers were already written. Wanted to override status code 400 with 404`. Not only that, the `c.AbortWithError()` will force the response to text/plain as you can see in this [issue](https://github.com/gin-gonic/gin/issues/633).

So the point of using `ShouldBindJSON()` is to handle the error by ourselves not by the gin itself. Just try to change your code 
```go
if err := cobs.Binding.BindingJSON(c, &userCobs); err != nil {
	cobs.Res.CustomResponse(c, "Content-Type", "application/json", "error", "failed when binding data", http.StatusNotFound, nil)
	return
}
```
to this
```go
if err := c.ShouldBindJSON(&userCobs); err != nil {
	cobs.Res.CustomResponse(c, "Content-Type", "application/json", "error", err.Error(), http.StatusNotFound, nil)
	return
}
```
Then you start your silly request with your postman and see the difference.

2020-09-24 16:18 UTC, huf0813 commented
Thx, i'll delete that later 👍. Don't feel bothered by me okay hahaha

2020-09-24 16:48 UTC, Endrawan commented
Yeah, chill man. It's just a discussion nothing wrong with it

2020-09-25 07:08 UTC, Endrawan approved these changes
It's all good now. Thank you! @huf0813

2020-09-25 07:09 UTC, merged